@startuml

class DefaultException {
    +DefaultException()
    +DefaultException(String message)
}

class CannotBeBlankException {
    +CannotBeBlankException()
    +CannotBeBlankException(String message)
}

class Exception {

}

class Company {

}

class Employee {

}

class Manager {

}

class Director {

}

class Intern {

}

abstract class Factory {

}

Exception <|-- DefaultException
Exception <|-- CannotBeBlankException


CannotBeBlankException <|.. Employee
DefaultException <|.. Employee

DefaultException <|.. Intern

DefaultException <|.. Manager

DefaultException <|.. Director

CannotBeBlankException <|.. Company
DefaultException <|.. Company

CannotBeBlankException <|.. Factory
DefaultException <|.. Factory

@enduml